### ISSUE TITLE
Version 0.0.12 is not posting the test result in the report

### ISSUE THREAD

**Issue by Pimagra** [Virtim/wdio-v6-testrail-reporter#2]
Node version : 10.21.0
SO : macOS Catalina (10.15.5)
WDIO : 6.3.0
Framework: Mocha

**Description :** 
The test run is created in Testrail but the result of the test case is not posted, the test is marked as "untested"

**Config file :**

const TestRailReporter = require('wdio-v6-testrail-reporter');
...
reporters: ['spec', [TestRailReporter, {
        testRailUrl: 'xxxx.testrail.io',
        username: 'xxx@xxx.com',
        password: 'xxxxxx,
        projectId: 1,
        suiteId: 1,
        runName: "Example",
        includeAll: true,
    }]], 
...

**Test:**
describe('Example Test', function() {
    it("C1", function() {
        expect(true).toBe(true);
    });
});

**Debugger:**

INFO wdio-testrail-reporter: Publishing 1 test result(s) to xxxx.testrail.io

**Comment by Virtim** [comment]
Hi, thanks for reporting this! I'm aware of this issue and working on a solution.

**Comment by Virtim** [comment]
Hey @Pimagra . I made a significant change and refactor in the last version. It's reporting properly now but going through a lot of hoops to do so. I'm not sure if this is a solution you were looking for but I wasn't able to find a better way, unfortunately.  I'll keep working on this reporter and hopefully will be able to make it better.

**Comment by raunybaez** [comment]
Hi Virtim, was this issue reported above fixed? I'm on version 0.0.13 but still facing the same issue.
